version: '3.8'

services:
  mysql:
    image: mysql:8
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: 1100
      MYSQL_DATABASE: msv-users
    ports:
      - "3306:3306"
    volumes:
      - ./db/mysql:/var/lib/mysql

  postgres:
    image: postgres:16-alpine
    container_name: postgres_db
    environment:
      POSTGRES_DB: msv-courses
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1100
    ports:
      - "5432:5432"
    volumes:
      - ./db/postgres:/var/lib/postgresql/data

